version: "3.5"

services:

  webserver:
    build: 
      context: ../
      dockerfile: ./deploy/bin/webserver/Dockerfile
    container_name: '7.1.x-webserver'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - mysql
    volumes: 
      - ../${PROJECT_NAME-deploy/www}:/var/www/html
      - ../${PHP_INI-deploy/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ../${VHOSTS_DIR-deploy/config/vhosts}:/etc/apache2/sites-enabled
      - ../${APACHE_LOG_DIR-deploy/logs/apache2}:/var/log/apache2

  mysql:
    image: mysql:5.7.22
    container_name: '5.7-mysql'
    restart: unless-stopped
    expose: 
      - "3306"
    volumes: 
      - mysql_data:/var/lib/mysql
      - ../${MYSQL_LOG_DIR-deploy/logs/mysql}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-tiger}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - phpmyadmin_sessions:/sessions

  redis:
    container_name: 'sc-redis'
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  phpmyadmin_sessions: