version: "3.5"

services:

  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.1.x-webserver'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - mysql
    volumes: 
      - ${DCL_PROJECT_ROOT-./www}:/var/www/html
      - ${DCL_PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${DCL_VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${DCL_APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2

  mysql:
    image: mysql:5.7.22
    container_name: '5.7-mysql'
    restart: unless-stopped
    expose: 
      - "3306"
    volumes: 
      - mysql_data:/var/lib/mysql
      - ${DCL_MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DCL_MYSQL_ROOT_PASSWORD-tiger}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - phpmyadmin_sessions:/sessions

  redis:
    container_name: 'sc-redis'
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  phpmyadmin_sessions: